# إعدادات الذاكرة لمنع انقطاع السيرفر وتجنب تعارض Kotlin DSL
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.kotlin.dsl.precompiled.script.plugins=false

# تفعيل المكتبات الحديثة AndroidX
android.useAndroidX=true
android.enableJetifier=true

# تحسين سرعة البناء والأداء
org.gradle.caching=true
org.gradle.parallel=true
